# Generated by Django 3.1.6 on 2021-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210224_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='exipiry_time',
            field=models.DateTimeField(null=True),
        ),
    ]
