# Generated by Django 3.1.6 on 2021-02-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210224_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='exipiry_time',
            new_name='expiry_time',
        ),
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
