# Generated by Django 3.1.6 on 2021-02-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_note_isset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
