# Generated by Django 3.1.6 on 2021-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210227_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
